import avatar1 from './avatar-6.jpg';
import avatar2 from './avatar-7.jpg';
import avatar3 from './avatar-8.jpg';

const tasks = [
    {
        id: 1,
        Descripcion: 'Ubold v3.0 - Redesign',
        status: 'Pending',
        Unidad: 'UN',
        image: avatar1,
        idCategoria: 'TABLEROS NORMALES',
        ValorUnitario: 28,
        Cantidad: 1,
        Codigo: 'NP019',
        maj: 'Jul 18, 2019',
    },
    {
        id: 2,
        Descripcion: 'Minton v3.0 - Redesign',
        status: 'Pending',
        Unidad: 'UN',
        image: avatar2,
        idCategoria: 'TABLEROS NORMALES',
        ValorUnitario: 21,
        Cantidad: 1,
        Codigo: 'NP017',
        maj: 'Jul 20, 2019',
    },
    {
        id: 3,
        Descripcion: 'Hyper v2.1 - Angular and Django',
        status: 'Pending',
        Unidad: 'UN',
        image: avatar1,
        idCategoria: 'TABLEROS NORMALES',
        ValorUnitario: 24,
        Cantidad: 1,
        Codigo: 'NP015',
        maj: 'Jul 21, 2019',
    },
    {
        id: 4,
        Descripcion: 'Hyper v2.1 - React, Webpack',
        status: 'Pending',
        Unidad: 'UN',
        image: avatar2,
        idCategoria: 'TABLEROS NORMALES',
        ValorUnitario: 21,
        Cantidad: 1,
        Codigo: 'NP014',
        maj: 'Jul 22, 2019',
    },
    {
        id: 5,
        Descripcion: 'Hyper 2.2 - Vue.Js and Laravel',
        status: 'Pending',
        Unidad: 'ML',
        image: avatar3,
        idCategoria: 'TABLEROS NORMALES',
        ValorUnitario: 2,
        Cantidad: 1,
        Codigo: 'NP013',
        maj: 'Jul 18, 2019',
    },
    {
        id: 6,
        Descripcion: 'Hyper 2.3 - Rails, NodeJs, Mean',
        status: 'Pending',
        Unidad: 'ML',
        image: avatar2,
        idCategoria: 'TABLEROS NORMALES',
        ValorUnitario: 24,
        Cantidad: 1,
        Codigo: 'NP012',
        maj: 'Jul 21, 2019',
    },
    {
        id: 7,
        Descripcion: 'Hyper - Landing page and UI Kit',
        status: 'Pending',
        Unidad: 'GL',
        image: avatar3,
        idCategoria: 'TABLEROS NORMALES',
        ValorUnitario: 11,
        Cantidad: 1,
        Codigo: 'NP011',
        maj: 'Jul 10, 2019',
    },
    {
        id: 8,
        Descripcion: 'Hyper 3.0 - Scoping',
        status: 'Pending',
        Unidad: 'GL',
        image: avatar2,
        idCategoria: 'TABLEROS NORMALES',
        ValorUnitario: 10,
        Cantidad: 1,
        Codigo: 'NP010',
        maj: 'Jul 24, 2019',
    },
];

export { tasks };
